---
Name: mimevalidator
---
MimeUploadValidator:
  MimeTypes:
    ico:
      - 'image/vnd.microsoft.icon'
      - 'image/x-icon'
      - 'image/x-ico'
    ics:
      - 'text/plain'
    xlsx:
      - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      - 'application/zip'
    docx:
      - 'application/zip'
